import { useState, useEffect, useRef } from 'react';
import './App.css';
import { useLoreMaster } from './hooks/useLoreMaster';
import { GemmaDownloadBar } from './components/GemmaDownloadBar';
import { LoreModal } from './components/LoreModal';

function App() {
  const [ws, setWs] = useState<WebSocket | null>(null);
  const [gameState, setGameState] = useState<any>(null);
  const [playerName, setPlayerName] = useState('');
  const [roomCode, setRoomCode] = useState('');
  const [playerId, setPlayerId] = useState('');
  const [proof, setProof] = useState('');
  const [displayedLore, setDisplayedLore] = useState<string | null>(null);

  const [wsReady, setWsReady] = useState(false);
  const loreMaster = useLoreMaster();
  const wsRef = useRef<WebSocket | null>(null);

  useEffect(() => {
    const socket = new WebSocket('wss://hacktober-fest-week-2-7n52.onrender.com/ws');
    
    socket.onopen = () => setWsReady(true);
    socket.onclose = () => setWsReady(false);

    socket.onmessage = (event) => {
      const data = JSON.parse(event.data);
      if (data.type === 'StateUpdate' || data.type === 'GameCreated' || data.type === 'GameJoined') {
        setGameState(data.payload.state);
        if (data.payload.player_id) {
          setPlayerId(data.payload.player_id);
        }
      }
      
      // If someone else completed a task and we receive lore, we can show it!
      if (data.type === 'StateUpdate' && data.payload.state.last_proof?.lore) {
         // Show lore generated by someone else in the room
         setDisplayedLore(data.payload.state.last_proof.lore);
      }
    };

    setWs(socket);
    wsRef.current = socket;

    return () => socket.close();
  }, []);

  const createGame = () => {
    ws?.send(JSON.stringify({ type: 'CreateGame', payload: { player_name: playerName } }));
  };

  const joinGame = () => {
    ws?.send(JSON.stringify({ type: 'JoinGame', payload: { room_code: roomCode, player_name: playerName } }));
  };

  const startGame = () => {
    ws?.send(JSON.stringify({ type: 'StartGame', payload: { room_code: gameState.room_code, player_id: playerId } }));
  };

  const completeTask = async () => {
    const task = gameState.tasks[gameState.current_task_index];
    
    // Generate lore using local WebGPU if ready
    let generatedLore = "";
    if (loreMaster.status === 'ready') {
      generatedLore = await loreMaster.generateLore(playerName, task.description);
      setDisplayedLore(generatedLore);
    }

    ws?.send(JSON.stringify({
      type: 'CompleteTask',
      payload: {
        room_code: gameState.room_code,
        player_id: playerId,
        proof: proof,
        lore: generatedLore // Note: Backend needs to support this optional field in TaskProof
      }
    }));
    
    setProof('');
  };

  if (!gameState) {
    return (
      <div className="App" style={{ padding: 20 }}>
        <h1>🌲 Outdoor Quest</h1>
        <GemmaDownloadBar loreMaster={loreMaster} />
        
        <div style={{ marginTop: 20 }}>
          <input placeholder="Player Name" value={playerName} onChange={e => setPlayerName(e.target.value)} />
          <button onClick={createGame} disabled={!wsReady || !playerName}>Create Game</button>
        </div>
        
        <div style={{ marginTop: 20 }}>
          <input placeholder="Room Code" value={roomCode} onChange={e => setRoomCode(e.target.value)} />
          <button onClick={joinGame} disabled={!wsReady || !playerName || !roomCode}>Join Game</button>
        </div>
      </div>
    );
  }

  return (
    <div className="App" style={{ padding: 20 }}>
      <h1>🌲 Room: {gameState.room_code}</h1>
      <GemmaDownloadBar loreMaster={loreMaster} />
      
      <h2>Status: {gameState.status}</h2>
      
      {gameState.status === 'Lobby' && (
        <button onClick={startGame}>Start Game</button>
      )}

      {gameState.status === 'InProgress' && (
        <div style={{ background: '#313244', padding: 15, borderRadius: 8, marginTop: 20 }}>
          <h3>Current Task: {gameState.tasks[gameState.current_task_index].title}</h3>
          <p>{gameState.tasks[gameState.current_task_index].description}</p>
          
          <input 
            placeholder="Photo Proof URL" 
            value={proof} 
            onChange={e => setProof(e.target.value)} 
          />
          <button onClick={completeTask} disabled={loreMaster.status === 'generating'}>
            {loreMaster.status === 'generating' ? 'Consulting Lore Master...' : 'Complete Task'}
          </button>
        </div>
      )}

      <LoreModal lore={displayedLore} onClose={() => setDisplayedLore(null)} />
    </div>
  );
}

export default App;
