import { useState, useEffect, useRef } from 'react';
import './App.css';
import { useLoreMaster } from './hooks/useLoreMaster';
import { GemmaDownloadBar } from './components/GemmaDownloadBar';
import { LoreModal } from './components/LoreModal';

function App() {
  const [ws, setWs] = useState<WebSocket | null>(null);
  const [gameState, setGameState] = useState<any>(null);
  const [playerName, setPlayerName] = useState('');
  const [roomCode, setRoomCode] = useState('');
  const [playerId, setPlayerId] = useState('');
  const [proof, setProof] = useState('');
  const [displayedLore, setDisplayedLore] = useState<string | null>(null);

  const [wsReady, setWsReady] = useState(false);
  const loreMaster = useLoreMaster();
  const wsRef = useRef<WebSocket | null>(null);

  useEffect(() => {
    const socket = new WebSocket('wss://hacktober-fest-week-2-7n52.onrender.com/ws');
    
    socket.onopen = () => setWsReady(true);
    socket.onclose = () => setWsReady(false);

    socket.onmessage = (event) => {
      const data = JSON.parse(event.data);
      if (data.type === 'StateUpdate' || data.type === 'GameCreated' || data.type === 'GameJoined') {
        setGameState(data.payload.state);
        if (data.payload.player_id) {
          setPlayerId(data.payload.player_id);
        }
      }
      
      // If someone else completed a task and we receive lore, we can show it!
      if (data.type === 'StateUpdate' && data.payload.state.last_proof?.lore) {
         // Show lore generated by someone else in the room
         setDisplayedLore(data.payload.state.last_proof.lore);
      }
    };

    setWs(socket);
    wsRef.current = socket;

    return () => socket.close();
  }, []);

  const createGame = () => {
    ws?.send(JSON.stringify({ type: 'CreateGame', payload: { player_name: playerName } }));
  };

  const joinGame = () => {
    ws?.send(JSON.stringify({ type: 'JoinGame', payload: { room_code: roomCode, player_name: playerName } }));
  };

  const startGame = () => {
    ws?.send(JSON.stringify({ type: 'StartGame', payload: { room_code: gameState.room_code, player_id: playerId } }));
  };

  const completeTask = async () => {
    const task = gameState.tasks[gameState.current_task_index];
    
    // Generate lore using local WebGPU if ready
    let generatedLore = "";
    if (loreMaster.status === 'ready') {
      generatedLore = await loreMaster.generateLore(playerName, task.description);
      setDisplayedLore(generatedLore);
    }

    ws?.send(JSON.stringify({
      type: 'CompleteTask',
      payload: {
        room_code: gameState.room_code,
        player_id: playerId,
        proof: proof,
        lore: generatedLore // Note: Backend needs to support this optional field in TaskProof
      }
    }));
    
    setProof('');
  };

  const handleProofUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      const reader = new FileReader();
      reader.onload = (ev) => {
        setProof(ev.target?.result as string);
      };
      reader.readAsDataURL(file);
    }
  };

  const leaveGame = () => {
    window.location.reload();
  };

  if (!gameState) {
    return (
      <div className="App" style={{ padding: 20 }}>
        <h1>🌲 Outdoor Quest</h1>
        <GemmaDownloadBar loreMaster={loreMaster} />
        
        <div style={{ marginTop: 20 }}>
          <input placeholder="Player Name" value={playerName} onChange={e => setPlayerName(e.target.value)} />
          <button onClick={createGame} disabled={!wsReady || !playerName}>Create Game</button>
        </div>
        
        <div style={{ marginTop: 20 }}>
          <input placeholder="Room Code" value={roomCode} onChange={e => setRoomCode(e.target.value)} />
          <button onClick={joinGame} disabled={!wsReady || !playerName || !roomCode}>Join Game</button>
        </div>
      </div>
    );
  }

  const isHost = gameState.players?.find((p: any) => p.id === playerId)?.is_host;

  return (
    <div className="App" style={{ padding: '20px', maxWidth: '800px', margin: '0 auto' }}>
      <GemmaDownloadBar loreMaster={loreMaster} />
      
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', margin: '20px 0' }}>
        <button 
          onClick={leaveGame}
          style={{ padding: '10px 15px', background: '#f38ba8', color: '#11111b', border: 'none', borderRadius: '6px', cursor: 'pointer', fontWeight: 'bold' }}
        >
          Leave Game
        </button>
        <h3 style={{ color: '#cdd6f4', margin: 0 }}>Status: {gameState.status}</h3>
      </div>

      <div style={{ background: '#1e1e2e', padding: '20px', borderRadius: '12px', textAlign: 'center', margin: '20px 0', border: '1px solid #313244' }}>
        <h2 style={{ margin: '0 0 15px 0', color: '#a6adc8', fontSize: '1.2em' }}>Room Code</h2>
        <div style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', gap: '15px' }}>
           <code style={{ fontSize: '2.5em', background: '#313244', padding: '10px 25px', borderRadius: '8px', color: '#a6e3a1', fontWeight: 'bold', letterSpacing: '2px' }}>
              {gameState.room_code}
           </code>
           <button 
             onClick={() => navigator.clipboard.writeText(gameState.room_code)}
             style={{ padding: '10px 15px', background: '#45475a', color: '#cdd6f4', border: 'none', borderRadius: '6px', cursor: 'pointer' }}
           >
             Copy
           </button>
        </div>
      </div>
      
      {gameState.status === 'Lobby' && (
        <div style={{ textAlign: 'center', padding: '30px' }}>
          <h2 style={{ color: '#cdd6f4', marginBottom: '20px' }}>Waiting for players...</h2>
          {isHost ? (
            <button 
              onClick={startGame}
              style={{ padding: '15px 30px', fontSize: '1.2em', background: '#89b4fa', color: '#11111b', fontWeight: 'bold', border: 'none', borderRadius: '8px', cursor: 'pointer' }}
            >
              Start Game
            </button>
          ) : (
            <p style={{ color: '#a6adc8', fontSize: '1.2em' }}>Waiting for the host to start the game...</p>
          )}
        </div>
      )}

      {gameState.status === 'InProgress' && (
        <div style={{ 
          background: 'linear-gradient(145deg, #313244, #1e1e2e)', 
          padding: '40px', 
          borderRadius: '16px', 
          marginTop: '30px',
          boxShadow: '0 10px 30px rgba(0,0,0,0.5)',
          border: '1px solid #45475a'
        }}>
          <div style={{ color: '#f9e2af', fontSize: '0.9em', textTransform: 'uppercase', letterSpacing: '2px', marginBottom: '10px', fontWeight: 'bold' }}>
            Active Quest
          </div>
          <h2 style={{ color: '#cdd6f4', margin: '0 0 15px 0', fontSize: '2.2em' }}>
            {gameState.tasks[gameState.current_task_index].title}
          </h2>
          <p style={{ color: '#a6adc8', fontSize: '1.2em', lineHeight: '1.6', marginBottom: '30px' }}>
            {gameState.tasks[gameState.current_task_index].description}
          </p>
          
          <div style={{ display: 'flex', flexDirection: 'column', gap: '15px' }}>
            <label style={{
              padding: '15px',
              borderRadius: '8px',
              border: '2px dashed #585b70',
              background: '#11111b',
              color: '#cdd6f4',
              fontSize: '1.1em',
              textAlign: 'center',
              cursor: 'pointer'
            }}>
              {proof ? "Photo Uploaded! Ready to complete." : "📸 Click to Upload Photo Proof"}
              <input 
                type="file" 
                accept="image/*"
                onChange={handleProofUpload} 
                style={{ display: 'none' }}
              />
            </label>
            <button 
              onClick={completeTask} 
              disabled={loreMaster.status === 'generating' || !proof}
              style={{
                background: loreMaster.status === 'generating' ? '#585b70' : '#89b4fa',
                color: '#11111b',
                padding: '15px',
                fontSize: '1.1em',
                fontWeight: 'bold',
                borderRadius: '8px',
                border: 'none',
                cursor: (loreMaster.status === 'generating' || !proof) ? 'not-allowed' : 'pointer',
                transition: 'background 0.2s'
              }}
            >
              {loreMaster.status === 'generating' ? '✨ Consulting Lore Master...' : 'Complete Quest'}
            </button>
          </div>
        </div>
      )}

      {gameState.players && gameState.players.length > 0 && (
        <div style={{ background: '#1e1e2e', padding: '20px', borderRadius: '12px', marginTop: '30px', border: '1px solid #313244' }}>
          <h3 style={{ margin: '0 0 15px 0', color: '#a6adc8' }}>Scoreboard</h3>
          <div style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
            {gameState.players.map((p: any) => (
              <div key={p.id} style={{ display: 'flex', justifyContent: 'space-between', padding: '12px', background: '#313244', borderRadius: '6px' }}>
                <span style={{ color: '#cdd6f4', fontWeight: 'bold' }}>{p.name} {p.is_host && '👑'}</span>
                <span style={{ color: '#a6e3a1', fontWeight: 'bold' }}>{p.score} pts</span>
              </div>
            ))}
          </div>
        </div>
      )}

      <LoreModal lore={displayedLore} onClose={() => setDisplayedLore(null)} />
    </div>
  );
}

export default App;
